### ISSUE TITLE
Error when using component helper with "fa-icon"

### ISSUE THREAD

**Issue by lindyhopchris** [martndemus/ember-font-awesome#175]
Hi,

Great addon, super useful.

With `4.0.0-alpha.10`, the following inside a component's template:

```hbs
{{yield (hash icon=(component "fa-icon" currentIcon))}}
```

Results in the following error:

```
Error: Assertion Failed: The component helper cannot be used without a valid component name. You used "fa-icon" via (component "fa-icon")
```

This isn't the case with `3.0.5`.

**Comment by cibernox** [comment]
That is expected, as the `{{fa-icon}}` component doesn't really exist, it is statically compiled in build time. 

It's a limitation of the approach used in v4.0 to make it much faster. It might be solvable, but it would be a non-trivial refactor. If you want more information on how to refactor can you ping me on the community slack?

**Comment by lindyhopchris** [comment]
@cibernox thanks for the quick reply. I'm able to work around it, so np.

The only thing that did occur to me though is that this does make it a bit counter-intuitive, particularly for newbies. I.e. I expect to be able to use the component helper to render a component, and to those who don't know, `fa-icon` appears to all intents and purposes a component!

Not at all suggesting you don't go with the new approach, as the performance improvement is totally worth it. But if there was a way of getting it working with the component helper that'd be great, if not then there needs to be a really clear message in the readme about this not being possible.

**Comment by cibernox** [comment]
I _believe_ it can be done but we might have to wait for the great module unification to land.

For now I would leave a clarification on the readme, but as soon as I have a few cycles I want to give it a try and investigate if I can replace it automatically.

**Comment by lindyhopchris** [comment]
Sounds like a plan! Well thanks for the work on this package, using it loads

**Comment by nmcclay** [comment]
I encountered this issue with a component that has prefix/suffix properties that accepted a fa-icon component declaration previously:
`{{input-textbox prefix=(component "fa-icon" "calendar") value=foobar}}`

This was handy because it would allow me to pass in any component or even just text values to my input's prefix property.

**Comment by buschtoens** [comment]
> I believe it can be done but we might have to wait for the great module unification to land.
> [...] I want to give it a try and investigate if I can replace it automatically.

By "replace it automatically" do you mean statically replacing all `(component "fa-icon" ...)` invocations with the transformed HTML? I would argue that this is next to impossible, since you cannot trace a passed `CurlyComponentDefinition` through JS land back into templates.

I think the best solution is (re-)adding a "real", tag-less `fa-icon` component that does nothing other than invoking `{{fa-icon ...}}` and proxying all arguments to that invocation. This way, all `{{fa-icon ...}}` invocations still get transformed to pure HTML, while `{{component "fa-icon" ...}}` will do the same internally.

**Comment by lindyhopchris** [comment]
@buschtoens this is a great solution, thanks for adding this in.
