### ISSUE TITLE
Include only required icons?

### ISSUE THREAD

**Issue by rwjblue** [martndemus/ember-font-awesome#57]
It might be possible to limit the icons returned in the `treeForVendor` hook to only include those that are actually in use (instead of 400+ when I might only be using 10).

The basic idea is:
- create a template AST transform that keeps track of all the icons.
- if only static strings are found (i.e. not bound properties for the icon name) we can filter the resulting vendor tree to include only the icons used
- if bound properties are used, include all icons

Credit for the idea to limit icon's emitted in vendor goes to @knownasilya in Slack.

**Comment by rwjblue** [comment]
I am unsure how to generate the custom font though, does fontawesome include tools for that?

**Comment by martndemus** [comment]
Nope, no tools from FA, although you can convert FA to svg using something like Icomoon

**Comment by knownasilya** [comment]
https://github.com/fontello/fontello#developers-api

**Comment by knownasilya** [comment]
What about using https://github.com/sunflowerdeath/broccoli-webfont. Looks like it's already being used by https://github.com/vitch/ember-cli-webfont. Basically you could include all icons by default, but then also have a config option that takes an array of icon names.

**Comment by martndemus** [comment]
I'm not going to implement this, but anyone who wants to do this, feel free to open a pull-request.

**Comment by buschtoens** [comment]
Font Awesome 5 Alpha 1 was released to Kickstarter backers. 🙋🏼‍♂️

It features a new SVG framework. In fact, it is now recommend to use SVG over web fonts. Depending on how this turns out, we might be able to do.so some really clever optimizations. I'm.gonna take a look at the release in the next says and see what's currently possible.

**Comment by buschtoens** [comment]
Fixed by
https://github.com/martndemus/ember-font-awesome/pull/158
https://github.com/martndemus/ember-font-awesome/pull/163
https://github.com/martndemus/ember-font-awesome/pull/167
https://github.com/martndemus/ember-font-awesome/pull/170
https://github.com/martndemus/ember-font-awesome/pull/182
https://github.com/martndemus/ember-font-awesome/pull/184
https://github.com/martndemus/ember-font-awesome/pull/187
